drop table food;

create table food (name varchar(50), ammt1 DECIMAL(4,2), ingredient1 varchar(255), ammt2 DECIMAL(4,2), ingredient2 varchar(255), ammt3 DECIMAL(4,2), ingredient3 varchar(255), ammt4 DECIMAL(4,2), ingredient4 varchar(255), ammt5 DECIMAL(4,2),ingredient5 varchar(255), ammt6 DECIMAL(4,2), ingredient6 varchar(255), ammt7 DECIMAL(4,2), ingredient7 varchar(255), ammt8 DECIMAL(4,2), ingredient8 varchar(255), ammt9 DECIMAL(4,2), ingredient9 varchar(255), ammt10 DECIMAL(4,2), ingredient10 varchar(255), ammt11 DECIMAL(4,2), ingredient11 varchar(255), ammt12 DECIMAL(4,2), ingredient12 varchar(255), ammt13 DECIMAL(4,2), ingredient13 varchar(255), ammt14 DECIMAL(4,2), ingredient14 varchar(255), ammt15 DECIMAL(4,2), ingredient15 varchar(255), prep text, description text);
SET SESSION sql_mode = '';

Insert into food values ('Buffalo Chicken Chowder',2, 'tablespoons butter' ,1, 'onion, diced' ,2, 'carrots, diced' ,2, 'stalks celery, diced' ,2, 'cloves garlic, chopped', 1/4, 'cup flour (rice flour for gluten free)' ,3, 'cups chicken broth or chicken stock' ,1, 'pound cooked chicken, diced or shredded' ,'', 'hot sauce to taste (I used 1/4 cup Franks Red Hot sauce)' ,1, 'large yukon gold or other boiling potato, peeled and cut into bite sized pieces' ,'', 'salt and pepper to taste' ,1, 'cup heavy cream' ,1/4, 'cup blue cheese, crumbled' ,'', '' ,'', '' ,'Melt the butter in a large sauce pan over medium-high heat, add the onion, carrots and celery and cook until tender, about 8-10 minutes. Add the garlic and cook until fragrant, about a minute. Mix in the flour and let it cook for 2-3 minutes. Add the chicken broth, chicken, hot sauce and potatoes, bring to a boil, reduce the heat and simmer until the potatoes are tender, about 10-15 minutes. Season with salt and pepper, mix in the cream and blue cheese and remove from heat when the cheese has melted.', 'Prep Time: 10 minutes Cook Time: 25 minutes Total Time: 35 minutes Servings: 4 A hearty and creamy chowder with all of the flavours of buffalo chicken wings!');
Insert into food values ('Greek Style Zucchini Salad' ,1/2, ' pound zucchini (grated)' ,1, ' tablespoon mint (chopped)' ,1, ' tablespoon dill (chopped)' ,1, ' green onion (sliced)' ,1/4, ' cup feta (crumbled)' ,1/2, ' lemon (juice and zest)' ,1, ' tablespoon olive oil' ,1, ' clove garlic (grated)' ,'' , 'salt and pepper to taste' ,'' ,'',''  ,'',''  ,'',''  ,'' ,'' ,'','' , '' ,  'Mix the zucchini, mint, dill,green onions and feta in a large bowl. Mix the lemon juice, zest, olive oil, garlic, salt and pepper in a small bowl. Toss the salad and the dressing. Chill in the fridge for several hours to overnight before serving.', 'Servings: 2');
Insert into food values ('Shrimp Scampi with Zucchini Noodles' ,'1', ' tablespoon olive oil' ,'2', ' tablespoons butter' ,'1', ' pound (16-24) shrimp, shelled and deveined' ,'4', ' cloves garlic, chopped' ,'1', ' pinch red pepper flakes (optional)' ,1/4, ' cup white wine or chicken broth or shrimp broth' ,'2', ' tablespoons lemon juice (~1 lemon)' ,'3', ' medium zucchini, cut into noodles' ,'', 'salt and pepper to taste' ,'1', ' teaspoon lemon zest' ,'1', ' tablespoon parsley, chopped' ,'', '' ,'', '' ,'', '' ,'', '' ,  'Heat the oil and melt the butter in a pan over medium-high heat until frothing, add the shrimp, cook for 2 minutes, flip, add the garlic and red pepper flakes and cook for 1 more minute before setting the shrimp aside. Add the white wine and lemon juice to the pan, deglaze it, simmer for 2 minutes, add the zucchini noodles and cook until just tender, about 2 minutes before seasoning with salt and pepper, adding the shrimp, lemon zest and parsley, tossing everything and removing from the heat.', 'Prep Time: 10 minutes Cook Time: 10 minutes Total Time: 20 minutes Servings: 4 Shrimp served in a lemony, garlicky and buttery sauce over a bed of light and fresh zucchini noodles, aka zoodles; a lighter take on shrimp scampi.');
Insert into food values ('Kolokythokeftedes (Zucchini and Feta Balls)' ,'2', ' cups zucchini, grated and squeezed' ,'1/4', ' cup of feta, crumbled' ,'1', ' splash ouzo (optional)' ,'1', ' clove garlic, chopped' ,'2', ' green onions, sliced' ,'1', ' handful herbs (such as mint, dill and parsley), chopped' ,'1', ' egg, lightly beaten' ,'', 'salt and pepper to taste' ,'~1/2', ' cup flour (I used whole wheat)' ,'', 'breadcrumbs (I use whole wheat)' ,'', 'oil for frying' ,'', '' ,'', '' ,'', '' ,'', '' ,  'Mix the zucchini, feta, ouzo, garlic, green onion, herbs and egg and season with salt and pepper. Mix in enough flour and breadcrumbs that you can work with the mixture to form balls. Form the mixture into balls and dust in flour. Fry in oil until golden brown and set aside to cool.', 'Prep Time: 10 minutes Cook Time: 15 minutes Total Time: 25 minutes Servings: 4 Zucchini, feta and plenty of fresh herbs rolled into balls and fried until light and crispy and golden brown!');


